figures:
  latency-and-goodput-vs-load-social-1:
    type: latency-and-goodput-vs-load
    include:
      latency-and-goodput-vs-load-social-1-dagor:
        label: Dagor
      latency-and-goodput-vs-load-social-1-rajomon:
        label: Rajomon
      latency-and-goodput-vs-load-social-1-sidecar:
        label: Roshanfer
  
  latency-and-goodput-vs-load-social-3:
    type: latency-and-goodput-vs-load
    include:
      latency-and-goodput-vs-load-social-3-dagor:
        label: Dagor
      latency-and-goodput-vs-load-social-3-rajomon:
        label: Rajomon
      latency-and-goodput-vs-load-social-3-sidecar:
        label: Roshanfer
  
  latency-and-rate-vs-time-social-1:
    type: latency-and-rate-vs-time
    include:
      latency-and-rate-vs-time-social-1-dagor:
        label: Dagor
        unit: "latency-and-rate-vs-time-social-1-dagor-rate-600"
        repeat: 5
      latency-and-rate-vs-time-social-1-rajomon:
        label: Rajomon
        unit: "latency-and-rate-vs-time-social-1-rajomon-rate-600"
        repeat: 6
      latency-and-rate-vs-time-social-1-sidecar:
        label: Roshanfer
        unit: "latency-and-rate-vs-time-social-1-sidecar-rate-600"
        repeat: 3

  max-queue-social-1:
    type: max-queue
    include:
      max-queue-social-1-dagor:
        label: Dagor
      max-queue-social-1-rajomon:
        label: Rajomon
      max-queue-social-1-sidecar:
        label: Roshanfer
  
  max-queue-social-3:
    type: max-queue
    include:
      max-queue-social-3-dagor:
        label: Dagor
      max-queue-social-3-rajomon:
        label: Rajomon
      max-queue-social-3-sidecar:
        label: Roshanfer
  
  resource-waste-bar-social-1:
    type: resource-waste-bar
    include:
      resource-waste-social-1-dagor:
        label: Dagor
      resource-waste-social-1-rajomon:
        label: Rajomon