figures:
  latency-and-goodput-vs-load-hotel-1:
    type: latency-and-goodput-vs-load
    include:
      latency-and-goodput-vs-load-hotel-1-envoy:
        label: Envoy
      latency-and-goodput-vs-load-hotel-1-plain:
        label: Plain
      latency-and-goodput-vs-load-hotel-1-sidecar:
        label: Roshanfer