figures:
  latency-vs-throughput-hotel:
    type: latency-vs-throughput
    include:
      latency-vs-throughput-hotel-search-hotel-sidecar:
        label: Roshanfer
      latency-vs-throughput-hotel-search-hotel-plain:
        label: Plain
