figures:
  latency-and-goodput-vs-load-hotel:
    type: latency-and-goodput-vs-load
    include:
      latency-and-goodput-vs-load-hotel-sidecar:
        label: Roshanfer
      latency-and-goodput-vs-load-hotel-rajomon:
        label: Rajomon
      latency-and-goodput-vs-load-hotel-dagor:
        label: Dagor
  
  latency-and-goodput-vs-load-hotel-2:
    type: latency-and-goodput-vs-load
    include:
      latency-and-goodput-vs-load-hotel-2-sidecar:
        label: Roshanfer
      latency-and-goodput-vs-load-hotel-2-rajomon:
        label: Rajomon
      latency-and-goodput-vs-load-hotel-2-dagor:
        label: Dagor
  
  latency-and-rate-vs-time-hotel:
    type: latency-and-rate-vs-time
    include:
      latency-and-rate-vs-time-hotel-sidecar:
        label: Roshanfer
        unit: "latency-and-rate-vs-time-hotel-sidecar-rate-10000"
        repeat: 0
      latency-and-rate-vs-time-hotel-rajomon:
        label: Rajomon
        unit: "latency-and-rate-vs-time-hotel-rajomon-rate-10000"
        repeat: 2
      latency-and-rate-vs-time-hotel-dagor:
        label: Dagor
        unit: "latency-and-rate-vs-time-hotel-dagor-rate-10000"
        repeat: 1

  max-queue-hotel:
    type: max-queue
    include:
      max-queue-hotel-sidecar:
        label: Roshanfer
      max-queue-hotel-rajomon:
        label: Rajomon
      max-queue-hotel-dagor:
        label: Dagor
  
  max-queue-hotel-2:
    type: max-queue
    include:
      max-queue-hotel-2-sidecar:
        label: Roshanfer
      max-queue-hotel-2-rajomon:
        label: Rajomon
      max-queue-hotel-2-dagor:
        label: Dagor
  
  resource-waste-bar-hotel:
    type: resource-waste-bar
    include:
      resource-waste-hotel-sidecar:
        label: Roshanfer
      resource-waste-hotel-rajomon:
        label: Rajomon
      resource-waste-hotel-dagor:
        label: Dagor
  
  resource-waste-bar-hotel-2:
    type: resource-waste-bar
    include:
      resource-waste-hotel-2-rajomon:
        label: Rajomon
      resource-waste-hotel-2-dagor:
        label: Dagor
  
  latency-vs-throughput-hotel:
    type: latency-vs-throughput
    include:
      latency-vs-throughput-hotel-sidecar:
        label: Roshanfer
      latency-vs-throughput-hotel-plain:
        label: Plain
