figures:
  latency-vs-throughput-chain1:
    type: latency-vs-throughput
    include:
      latency-vs-throughput-chain1-sidecar-oc-0:
        label: 0%
      latency-vs-throughput-chain1-sidecar-oc-20:
        label: 20%
      latency-vs-throughput-chain1-sidecar-oc-60:
        label: 60%
      latency-vs-throughput-chain1-sidecar-oc-100:
        label: 100%