figures:
  latency-vs-throughput-chain2:
    type: latency-vs-throughput
    include:
      latency-vs-throughput-chain2-sidecar:
        label: Roshanfer
      latency-vs-throughput-chain2-plain:
        label: Plain
      latency-vs-throughput-chain2-envoy:
        label: Envoy